### PR TITLE
Fix probabilities shown in scoreboard

### PR DESCRIPTION
**Pull request by L-as**
The logic was incorrect.

### CODE REVIEW

**Comment by L-as** [comment]
BTW I have not tested this, but @TheRealNin told me to do it anyway.

**Comment by GhoulofGSG9** [comment]
Thanks for the PR. I didn't directly merge it because you overwrote the avg. skill vars that are used to display the teams average skill.

**Comment by L-as** [comment]
Average skills do now not work. No script errors as far as I can see.

**Comment by GhoulofGSG9** [comment]
Did you re-enable it? I did reset the given server options as mentioned in the change log so server ops opt into those features again.

**Comment by L-as** [comment]
Yes, I did.

**Comment by GhoulofGSG9** [comment]
Could you post the server's ns2plus config?

**Comment by L-as** [comment]
```json
{
  "allow_ambient":true,
  "allow_deathstats":true,
  "allow_drawviewmodel":false,
  "allow_mapparticles":true,
  "allow_nsllights":true,
  "autodisplayendstats":true,
  "endstatsteambreakdown":true,
  "modupdater":false,
  "modupdatercheckinterval":15,
  "modupdaterreminderinterval":2,
  "savestats":false,
  "showavgteamskill":true,
  "showplayerskill":false,
  "showprobabilityofteamvictory":false
}
```

**Comment by GhoulofGSG9** [comment]
@Laaas Somehow your config failed to upgrade. The hive skill related options have now a `show_` prefix (so e.g. showavgteamskill is now called show_avgteamskill). Checking other servers the config upgraded just fine so I think you may have a file access rights conflict at your server.

**Comment by L-as** [comment]
Thanks! That makes a lot of sense.

**Pull request closed without merging**
